name: bip39
description: Dart implementation of Bitcoin BIP39 Mnemonic code for generating deterministic keys
version: 1.1.0
homepage: https://github.com/wstueve/bip39

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  pointycastle: ^3.7.3
  hex: ^0.2.0
  crypto: ^3.0.0
dev_dependencies:
  test: ^1.0.0
